name: openpiv
dependencies:
- cycler=0.10.0
- decorator=4.0.9
- freetype=2.5.5
# - jbig=2.1
- jpeg=8d
- libpng=1.6.17
- libtiff=4.0.6
- matplotlib=1.5.1
- mkl=11.3.1
- networkx=1.11
- numpy=1.11.0
- openssl=1.0.2g
- pillow=3.2.0
- pip=8.1.1
- progressbar2>=3.8.1
- pyparsing=2.1.1
- pyqt=4.11.4
- python=2.7.11
- python-dateutil=2.5.2
- pytz=2016.3
- qt=4.8.7
# - readline=6.2
- scikit-image=0.12.3
- scipy=0.17.0
- setuptools=20.7.0
- sip=4.16.9
- six=1.10.0
- sqlite=3.9.2
- tk=8.5.18
- wheel=0.29.0
# - xz=5.0.5
- zlib=1.2.8
- notebook=4.2.1
- nose=1.3.7
- cython=0.24.1
