package:
  name: openpiv
  version: "0.21.2"

source:
  git_rev: 0.21.2
  git_url: https://github.com/openpiv/openpiv-python.git

requirements:
  build:
    - python
    - pip
    - setuptools
    - numpy
    - cython
    - requests
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - scikit-image
    - progressbar2
    - future

test:
  imports:
    - openpiv

about:
  home: https://github.com/openpiv/openpiv
  license: GPLv3
  license_file: LICENSE.txt
  summary: "Open Source Particle Image Velocimetry"
  doc_url: http://openpiv.readthedocs.io/
